name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - pandas
    - tqdm
    - pip:
        - tensorflow
        - TFLearn
        - git+https://github.com/fchollet/keras.git
